DOMAIN = "bjp_label"
VERSION = "0.4.5"

FRONTEND_URL = "/bjp_label"

CONF_PRINTER_BACKEND = "printer_backend"
CONF_DEVICE_ID = "device_id"
CONF_HOST = "host"
CONF_LABEL_SIZE = "label_size"
CONF_FONT = "font"
CONF_PORT = "port"

PRINTER_BACKEND_NIIMBOT = "niimbot"
PRINTER_BACKEND_XPRINTER_TSPL = "xprinter_tspl"
PRINTER_BACKENDS = [PRINTER_BACKEND_NIIMBOT, PRINTER_BACKEND_XPRINTER_TSPL]

LABEL_SIZE_100X75 = "100x75"
LABEL_SIZE_100X150 = "100x150"
LABEL_SIZES = [LABEL_SIZE_100X75, LABEL_SIZE_100X150]

DEFAULT_PRINTER_BACKEND = PRINTER_BACKEND_NIIMBOT
DEFAULT_FONT = "NotoSansThai-Regular.ttf"
DEFAULT_WIDTH = 640
DEFAULT_HEIGHT = 384
DEFAULT_DENSITY = 3
DEFAULT_ROTATE = 90
DEFAULT_LABEL_SIZE = LABEL_SIZE_100X75
DEFAULT_PORT = 9100

SERVICE_PRINT_LABEL = "print_label"
SERVICE_GET_SETTINGS = "get_settings"
SERVICE_SAVE_CUSTOMER = "save_customer"
SERVICE_SEARCH_CUSTOMERS = "search_customers"
SERVICE_PRINT_CUSTOMER = "print_customer"
