DOMAIN = "bjp_label"

CONF_DEVICE_ID = "device_id"
CONF_FONT = "font"

DEFAULT_FONT = "NotoSansThai-Regular.ttf"
DEFAULT_WIDTH = 400
DEFAULT_HEIGHT = 640
DEFAULT_DENSITY = 3
DEFAULT_ROTATE = 90

SERVICE_PRINT_LABEL = "print_label"
SERVICE_SAVE_CUSTOMER = "save_customer"
SERVICE_SEARCH_CUSTOMERS = "search_customers"
SERVICE_PRINT_CUSTOMER = "print_customer"
